"""
V12 Phase 2: Train GNN TypeClassifier on DDIM-generated coordinates.

Key: GNN is trained on coordinates generated by the frozen diffusion model,
so training and inference see the same coordinate distribution — no exposure bias.

Usage:
    python -m src.train_gnn \
        --diffusion_checkpoint experiments/v12/checkpoints/best_diffusion.pt \
        --epochs 30 \
        --save_dir experiments/v12/gnn_checkpoints
"""

import os
import sys
import json
import argparse
import time

import numpy as np
import torch
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm

from src.data.dataset import QUAMAFMDataset, create_dataloaders, MAX_ATOMS, NUM_ATOM_TYPES
from src.train import AFM3DReconModel
from src.models.gnn_type_classifier import GNNTypeClassifier


@torch.no_grad()
def generate_training_data(model, loader, device, num_samples=10000, ddim_steps=50):
    """Generate coordinates using frozen diffusion model for GNN training.

    Returns lists of (generated_coords, gt_types, c_patches, mask).
    """
    model.eval()
    all_coords = []
    all_types = []
    all_patches = []
    all_masks = []
    all_afm = []
    count = 0

    pbar = tqdm(loader, desc="Generating GNN training data")
    for batch in pbar:
        if count >= num_samples:
            break
        batch = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in batch.items()}

        afm = batch["afm_stack"]
        c_global, c_patches = model.encoder(afm)
        n_atoms = model.count_head.predict(c_global)

        # Generate coordinates with DDIM
        ring_info = None
        if "ring_atom_indices" in batch:
            ring_info = {
                "ring_atom_indices": batch["ring_atom_indices"],
                "ring_templates": batch["ring_templates"],
                "ring_valid": batch["ring_valid"],
            }

        from src.models.diffusion import compute_shape_descriptors
        pred_shape = model.shape_head(c_global)

        coords, _ = model.ddpm.sample(
            c_global, c_patches, n_atoms, max_atoms=MAX_ATOMS,
            ring_info=ring_info, use_ddim=True, ddim_steps=ddim_steps,
            use_physics_guidance=True, target_shape=pred_shape,
        )

        # Build mask
        B = coords.shape[0]
        mask = torch.zeros(B, MAX_ATOMS, device=device)
        for i in range(B):
            mask[i, :n_atoms[i]] = 1.0

        all_coords.append(coords.cpu())
        all_types.append(batch["atom_types"].cpu())
        all_patches.append(c_patches.cpu())
        all_masks.append(mask.cpu())
        all_afm.append(batch["afm_stack"].cpu())
        count += B
        pbar.set_postfix(n=count)

    return {
        "coords": torch.cat(all_coords)[:num_samples],
        "types": torch.cat(all_types)[:num_samples],
        "patches": torch.cat(all_patches)[:num_samples],
        "masks": torch.cat(all_masks)[:num_samples],
        "afm": torch.cat(all_afm)[:num_samples],
    }


def train_gnn(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Load diffusion model
    state = torch.load(args.diffusion_checkpoint, map_location=device, weights_only=False)
    config = state["config"]
    config["num_cids"] = 0

    model = AFM3DReconModel(config).to(device)
    model.load_state_dict(state["model"], strict=False)
    model.eval()
    print(f"Loaded diffusion model from {args.diffusion_checkpoint} (epoch {state.get('epoch', '?')})")

    # Data loaders
    train_loader, val_loader, _, _ = create_dataloaders(
        data_root=config["data_root"], param_key=config["param_key"],
        img_size=config["img_size"], min_corrugation=config["min_corrugation"],
        augment_rotation=False, require_ring=config.get("require_ring", False),
        batch_size=config["batch_size"], num_workers=0,
        max_samples=config["max_samples"], val_size=config["val_size"],
    )

    # Generate training data
    print(f"\nGenerating GNN training data ({args.num_gen_samples} samples)...")
    gen_data = generate_training_data(model, train_loader, device,
                                       num_samples=args.num_gen_samples,
                                       ddim_steps=args.ddim_steps)
    print(f"Generated {len(gen_data['coords'])} samples")

    # Generate validation data
    print(f"Generating GNN validation data...")
    val_data = generate_training_data(model, val_loader, device,
                                       num_samples=min(1000, len(val_loader.dataset)),
                                       ddim_steps=args.ddim_steps)
    print(f"Generated {len(val_data['coords'])} val samples")

    # Create data loaders for GNN training (includes AFM stacks)
    train_dataset = TensorDataset(
        gen_data["coords"], gen_data["types"], gen_data["patches"],
        gen_data["masks"], gen_data["afm"],
    )
    val_dataset = TensorDataset(
        val_data["coords"], val_data["types"], val_data["patches"],
        val_data["masks"], val_data["afm"],
    )
    gnn_train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
    gnn_val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)

    # Noise injection std (0.01 normalized ≈ 0.12Å, small enough to preserve bond length info)
    noise_std = 0.01

    # Create GNN
    gnn = GNNTypeClassifier(
        cond_dim=config["embed_dim"],
        hidden_dim=128,
        num_gnn_layers=4,
        num_types=NUM_ATOM_TYPES,
    ).to(device)

    gnn_params = sum(p.numel() for p in gnn.parameters())
    print(f"GNN parameters: {gnn_params / 1e6:.2f}M")

    # Optimizer
    optimizer = optim.AdamW(gnn.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs, eta_min=1e-5)

    # Training loop
    os.makedirs(args.save_dir, exist_ok=True)
    best_val_loss = float("inf")

    for epoch in range(1, args.epochs + 1):
        gnn.train()
        total_loss = 0
        n_batches = 0

        for coords, types, patches, masks, afm in tqdm(gnn_train_loader, desc=f"GNN [{epoch}/{args.epochs}]", leave=False):
            coords, types, patches, masks, afm = (
                coords.to(device), types.to(device), patches.to(device),
                masks.to(device), afm.to(device),
            )

            # Noise injection: small Gaussian noise for robustness (σ=0.01 ≈ 0.12Å)
            noisy_coords = coords + noise_std * torch.randn_like(coords) * masks.unsqueeze(-1)

            loss = gnn.compute_loss(noisy_coords, patches, types, masks, afm_stack=afm)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(gnn.parameters(), max_norm=1.0)
            optimizer.step()

            total_loss += loss.item()
            n_batches += 1

        scheduler.step()
        train_loss = total_loss / max(n_batches, 1)

        # Validation
        gnn.eval()
        val_total = 0
        val_correct = 0
        val_n = 0
        with torch.no_grad():
            for coords, types, patches, masks, afm in gnn_val_loader:
                coords, types, patches, masks, afm = (
                    coords.to(device), types.to(device), patches.to(device),
                    masks.to(device), afm.to(device),
                )

                logits = gnn(coords, patches, masks, afm_stack=afm)
                pred = logits.argmax(dim=-1)
                valid = (masks > 0) & (types >= 0)
                val_correct += ((pred == types) & valid).sum().item()
                val_n += valid.sum().item()

                val_loss = gnn.compute_loss(coords, patches, types, masks, afm_stack=afm)
                val_total += val_loss.item()

        val_acc = val_correct / max(val_n, 1)
        val_loss_mean = val_total / max(len(gnn_val_loader), 1)

        print(f"Epoch {epoch:3d}/{args.epochs} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss_mean:.4f} | Val Type Acc: {val_acc:.4f}")

        # Save best
        if val_loss_mean < best_val_loss:
            best_val_loss = val_loss_mean
            torch.save({
                "epoch": epoch,
                "gnn": gnn.state_dict(),
                "val_loss": val_loss_mean,
                "val_acc": val_acc,
            }, os.path.join(args.save_dir, "best_gnn.pt"))

        if epoch % 10 == 0:
            torch.save({
                "epoch": epoch,
                "gnn": gnn.state_dict(),
                "val_acc": val_acc,
            }, os.path.join(args.save_dir, f"gnn_epoch_{epoch}.pt"))

    print(f"\nGNN training complete. Best val loss: {best_val_loss:.4f}")
    print(f"Checkpoints saved to: {args.save_dir}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train GNN TypeClassifier (V12 Phase 2)")
    parser.add_argument("--diffusion_checkpoint", type=str, required=True)
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--num_gen_samples", type=int, default=5000,
                        help="Number of samples to generate for GNN training")
    parser.add_argument("--ddim_steps", type=int, default=50)
    parser.add_argument("--save_dir", type=str, default="experiments/v12/gnn_checkpoints")
    args = parser.parse_args()

    train_gnn(args)
